### ISSUE TITLE
Dead links with undefined fix

### ISSUE THREAD

**Issue by jean-roland** [atolab/zenoh-web#13]
I noticed 4 more dead links on "zenoh-web/content/docs/getting-started/first-app.md" at the end:

``` - **Rust**: https://github.com/eclipse-zenoh/zenoh/tree/master/zenoh/examples/zenoh
 - **Rust (zenoh-net)**: https://github.com/eclipse-zenoh/zenoh/tree/master/zenoh/examples/zenoh-net
 - **C (zenoh-net)**: https://github.com/eclipse-zenoh/zenoh-c/tree/master/examples/net
 - **Python**: https://github.com/eclipse-zenoh/zenoh-python/tree/master/examples/zenoh
 - **Python (zenoh-net)**: https://github.com/eclipse-zenoh/zenoh-python/tree/master/examples/zenoh-net
```
Problem is, it seems there is no longer a dinstinction between regular and zenoh-net examples, or I couldn't find them, so there was no easy fix.

**Comment by josuah** [comment]
Hello! I am new to Zenoh, so not sure about the history of the doc.
It is a link toward the `/getting-started/what-is-zenoh/`:

It is the link *to* the getting-started page on the very bottom of https://zenoh.io/docs/overview/what-is-zenoh/

![deadlink](https://user-images.githubusercontent.com/55351021/211810896-9547e004-261b-4ccc-9a30-3b1975911aa6.png)

Maybe the layout of this directory changed: https://github.com/atolab/zenoh-web/tree/master/content/docs/getting-started

**Comment by Mallets** [comment]
Hello @josuah , I've fixed the deadlink in the overview. Now it points to the right page. Thanks for reporting it!
