### ISSUE TITLE
Usecases page contains dead google docs link

### ISSUE THREAD

**Issue by oteffahi** [atolab/zenoh-web#52]
"Controlling a robot using Zenoh" use-case points to a dead link: https://github.com/atolab/zenoh-web/blob/0586bea48aad6aff754b7a3c0ca2dc70529698a5/content/usecases.md?plain=1#L13

**Comment by Charles-Schleich** [comment]
fixed by https://github.com/atolab/zenoh-web/commit/6d10baa58e790957bb3c5c671ce91fa5dccedc56
