### ISSUE TITLE
Update getting started to 1.0.0

### ISSUE THREAD

**Issue by Mallets** [atolab/zenoh-web#54]
Current [getting started guide](https://zenoh.io/docs/getting-started/first-app/) covers `0.11.0` release.
In addition to the [migration guide](https://github.com/atolab/zenoh-web/pull/51), the documentation should be update as well.

**Comment by Mallets** [comment]
@Charles-Schleich

**Comment by Charles-Schleich** [comment]
PR opened: https://github.com/atolab/zenoh-web/pull/55
We can merge when the migration guide PR goes through https://github.com/atolab/zenoh-web/pull/51.
